### ISSUE TITLE
Logo APP

### ISSUE THREAD

**Issue by wbolo** [ITISPR/OrtoCultura#1]
Creare il logo dell'applicazione.

**Comment by battioni** [comment]
Io farei il logo (che alla fine sarà anche l'icona dell'app) in stile material design.
Ad esempio:
![](http://materialdesignblog.com/wp-content/uploads/2015/04/Material_inspired_icon_pack_by__JurreHoutkamp_contents.png)
Inventati qualcosa!!!

**Comment by wbolo** [comment]
Si, facciamo tutto MaterialDesign anche se finirà su iPhone, oltre che Android.
